import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { UseAuthContext } from '../app/state/authContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UseAuthContext>
          {children}
        </UseAuthContext>
      </body>
    </html>
  );
};
