import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { UseAuthContext } from '../app/state/authContext';
import { ThemeProvider } from './state/themeState/themeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-[#242633]`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <UseAuthContext>
            {children}
          </UseAuthContext>
        </ThemeProvider>
      </body>
    </html>
  );
};
